africandesignmatters/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from fcm_django.api.rest_framework import FCMDeviceAuthorizedViewSet
from rest_framework.routers import DefaultRouter
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from blog.models import Post


info_dict= {
    "queryset": Post.objects.all(),
}



router = DefaultRouter()
router.register('devices', FCMDeviceAuthorizedViewSet)





urlpatterns = [
    path('tinymce/', include('tinymce.urls')),
    path('', include('pwa.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': {'blog': GenericSitemap(info_dict, priority=0.6)}},
         name='django.contrib.sitemaps.views.sitemap'),
    path('adm_slack/', include('adm_slack.urls')),
    path('moderator/', include('moderator.urls')),
    path('api/', include(router.urls)),
    # path("firebase-messaging-sw.js",
    #     TemplateView.as_view(
    #         template_name="firebase-messaging-sw.js",
    #         content_type="application/javascript",
    #     ),
    #     name="firebase-messaging-sw.js"
    # ),
    path('student/', include('student.urls')),
    path('orders/', include('orders.urls')),
    path('cart/', include('cart.urls')),
    path('shop/', include('shop.urls')),
    path('api/', include('api.urls')),
    path('studio/', include('studio.urls')),
    path('blog/', include('blog.urls')),
    path('payments/', include('payments.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('dashboard/', include('dashboard.urls')),
    # path('sw.js', TemplateView.as_view(template_name='sw.js', content_type='application/javascript'), name='sw.js'),
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)


handler404 = 'home.views.error_404'

api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .accounts.views import (
    UserViewset
)
from .studio.views import (
    ProjectViewset
)
from .blog.views import PostViewset

router = DefaultRouter()

router.register('posts', PostViewset, basename='posts')
router.register('projects', ProjectViewset, basename='projects')
router.register('users', UserViewset, basename='users' )

urlpatterns = [
    path('blog/', include(router.urls)),
    path('accounts/', include(router.urls)),
    path('studio/', include(router.urls)),
]

cart/urls.py
from django.urls import path

from .views import cart_detail, cart_add, cart_remove, cart_clear, validate_cart, stock_short

app_name = 'cart'


urlpatterns = [
    path('stock/short/<int:product_pk>', stock_short, name='stock_short'),
    path('validate/cart', validate_cart, name='validate_cart'),
    path('cart/clear', cart_clear, name='cart_clear'),
    path('', cart_detail, name='cart_detail'),
    path('add/product/<int:product_id>', cart_add, name='cart_add'),
    path('remove/product/<int:product_id>', cart_remove, name='cart_remove'),

]

orders/urls.py
from django.urls import path
from shop.models import (
    Product,
)



from django.urls import path
from .views import (
    warning, order_create, created
)

app_name = 'orders'

urlpatterns = [
    path('order/created/<int:order_pk>', created, name='created'),
    path('order/create', order_create, name='order_create'),
    path('multiple/vendor/warning', warning, name='warning'),
]

shop/urls.py
from django.urls import path
from .views import (
    products, product_detail, new_category, category_detail,
    categories, new_product, product_tags, review_product
)

app_name = 'shop'

urlpatterns = [
    path('review/<int:product_id>', review_product, name='review_product'),
    path('tagged/products/<tag>', product_tags, name='tagged_products'),
    path('new/product/<int:category_pk>', new_product, name='new_product'),
    path('categories', categories, name='categoriess'),
    path('category/<int:product_category_pk>', category_detail, name='category_detail'),
    path('new/category', new_category, name='new_category'),
    path('products', products, name='products'),
    path('product/<int:product_id>', product_detail, name='product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [
    (i, str(i)) for i in range(1, 21)
]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int
    )
    update = forms.BooleanField(
        required=False,
        initial=False,
        widget=forms.HiddenInput
    )
 


    
   

cart/views.py
from django.shortcuts import (
    render, get_object_or_404, redirect
)

from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
# from djmoney.serializers import Serializer
import json
from django.http import HttpResponse

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)

    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        if product.stock < cd['quantity']:
            return redirect('cart:stock_short', product.pk)
        else:

            cart.add(
                product=product,
                quantity=cd['quantity'],
                update_quantity=cd['update'],

            )
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={
                'quantity': item['quantity'],
                'update': True,

            }
        )

    return render(request, 'cart/detail.html', {
        'cart': cart,

    })


def cart_clear(request):
    cart = Cart(request)
    cart.clear()
    return render(request, 'cart/detail.html', {

    })


def validate_cart(request):
    cart = Cart(request)
    return render(request, 'cart/validation.html', {
        'cart': cart
    })


def stock_short(request, product_pk):
    product = get_object_or_404(Product, pk=product_pk)
    return render(request, 'cart/stock_short.html', {
        'product': product,
    })

cart/templates/cart/detail.html
{% extends 'home/header.html' %}
{% load static %}
{% load crispy_forms_tags %}
<!-- {% load djmoney %} -->





{% block content %}

<head>
	<!-- <link rel="stylesheet" href="{% static 'cart/css/cart.css' %}"> -->
	<style>
		li{
			list-style: none;
		}
	</style>
</head>

<section id="cart-heading">
	<div class="container headline">
		<h1>Your Cart</h1>
	</div>

</section>


<section id="cart-table">
	<div class="container">
		<table class="table">
			<thead>
				<tr class="center">
					<th></th>
					<th><span>Item</span></th>
					<th><span>Quantity</span></th>
					<th><span>Remove</span></th>
					<th><span>Unit price</span></th>
					<th> <span>Price</span></th>
				</tr>
			</thead>
			<tbody>
				{% for item in cart %}
				{% with product=item.product %}
				<tr class="center">
					<td>
						<a href="{{product.get_absolute_url}}">
							{% if product.image %}
							<div style="width: 80px; height: 80px;">
								<img  src="{{ product.image.url}}
                                  ">
							</div>

							{% endif %}
						</a>
					</td>
					<td>{{product.name}}</td>

					<td>
		
							<form style="display: inline-flex;" action="{% url 'cart:cart_add' product.id %}" method="POST">
								{% csrf_token %}
							
								{{item.update_quantity_form.quantity}}
								{{item.update_quantity_form.update}}
							
								<input type="submit" value="update">
							
							</form>				
					</td>
					<td>
						<a href="{% url 'cart:cart_remove' product.id %}">
							<span> <i class="fa fa-eraser red" title="Remove"></i></span>
						</a>
					</td>

					<td>GH₵ <span>{{item.total_price}}</span></td>
					<td>{{item.get_cost}}</td>


				</tr>
				{% endwith %}
				{% endfor %}
				<hr>
				<tr class="total">
					<td colspan="2"></td>
					<td>Total</td>

					<td class="price">GH₵ {{ cart.get_total_price }}</td>
				</tr>
			</tbody>

		</table>

	</div>

</section>

<section id="cart-menu">

<div class="container">
	<li><a class="btn btn-white" href="{% url 'cart:cart_clear' %}">Clear Cart</a>
	</li>
	
	<li><a class="btn btn-white" href="{% url 'shop:products' %}">
			<i class="fa fa-shopping-cart"></i> Continue shopping
		</a></li>
	
	<li>
		<a class="btn btn-white" href="{% url 'orders:order_create' %}">
			<i class="fa fa-check"></i> Proceed To Checkout
		</a>
	</li>

	<div id="coupon-form">
		<form  action="" method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			{{coupon_form|crispy}}
			<button class="btn btn-white" type="submit"> <i class="fa fa-ticket"></i> Apply
				Coupon</button>
	
		</form>
	</div>
</div>
	



</section>


{% endblock content %}

cart/templates/cart/stock_short.html
{% extends 'home/base.html' %}
{% load static %}



{% block title %}
    Stock Is Short
{% endblock title %}



{% block content %}

<head>
    <style>
        #short-stock{
            margin: 50px auto;
            width: 80%;
            min-height: 400px;
            text-transform: capitalize;
        }
        #short-stock h1{
            padding-top: 30px;
            width: 80%;
            margin: auto;
            text-align: center;
            font-size: 25px;
            min-height: 70px;
        }

         #short-stock p{
            width: 80%;
            text-align: center;
            font-size: 20px;
            padding-top: 50px;
            min-height: 70px;
            background-color: #425563;
            color: #FFFFFF;
            margin: 20px auto;
        }


         #short-stock a{
           padding: 15px;
           background-color: #FFFFFF;
           color: #425563;
           border-radius: 5px;
        }
    </style>
</head>

<section id="short-stock">
    <div class="container">
        <h1><span class="gas-color">{{vendor.company_name.title}}</span></h1>
        <p ><span class="highlight pt30 center"><a href="{% url 'shop:product_detail' product.pk %}">{{product.name}}</a></span> is less than the quantity you have chosen.</p>
      
        <p class="content">Please go back to your cart and amend or check other branches. Thanks</p>
    </div>

    <div class="container pt30 center">
        <a class="btn1" href="{% url 'cart:cart_detail' %}">Back To Cart</a>
    </div>
</section>
    
{% endblock content %}
    

cart/templates/cart/validation.html
{% extends 'homee/base.html' %}



{% block content %} 

        <div class="container">
            <p class="pop">You have chosen items from more than one vendor</p>
            <h6>Please continue to shop with one vendor or clear the cart. thanks</h6>
        </div>    
{% endblock content %}
    