africandesignmatters/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from fcm_django.api.rest_framework import FCMDeviceAuthorizedViewSet
from rest_framework.routers import DefaultRouter
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from blog.models import Post


info_dict= {
    "queryset": Post.objects.all(),
}



router = DefaultRouter()
router.register('devices', FCMDeviceAuthorizedViewSet)





urlpatterns = [
    path('tinymce/', include('tinymce.urls')),
    path('', include('pwa.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': {'blog': GenericSitemap(info_dict, priority=0.6)}},
         name='django.contrib.sitemaps.views.sitemap'),
    path('adm_slack/', include('adm_slack.urls')),
    path('moderator/', include('moderator.urls')),
    path('api/', include(router.urls)),
    # path("firebase-messaging-sw.js",
    #     TemplateView.as_view(
    #         template_name="firebase-messaging-sw.js",
    #         content_type="application/javascript",
    #     ),
    #     name="firebase-messaging-sw.js"
    # ),
    path('student/', include('student.urls')),
    path('orders/', include('orders.urls')),
    path('cart/', include('cart.urls')),
    path('shop/', include('shop.urls')),
    path('api/', include('api.urls')),
    path('studio/', include('studio.urls')),
    path('blog/', include('blog.urls')),
    path('payments/', include('payments.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('dashboard/', include('dashboard.urls')),
    # path('sw.js', TemplateView.as_view(template_name='sw.js', content_type='application/javascript'), name='sw.js'),
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)


handler404 = 'home.views.error_404'

api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .accounts.views import (
    UserViewset
)
from .studio.views import (
    ProjectViewset
)
from .blog.views import PostViewset

router = DefaultRouter()

router.register('posts', PostViewset, basename='posts')
router.register('projects', ProjectViewset, basename='projects')
router.register('users', UserViewset, basename='users' )

urlpatterns = [
    path('blog/', include(router.urls)),
    path('accounts/', include(router.urls)),
    path('studio/', include(router.urls)),
]

blog/urls.py
from django.urls import path
from .views import (
    posts, post_detail, new_post, post_reply
)
app_name = 'blog'



urlpatterns = [
    path('reply/<int:comment_pk>', post_reply, name='reply'),
    path('new/post', new_post, name='new_post'),
    path('posts', posts, name='posts'),
    path('post/<int:post_pk>', post_detail, name='post_detail'),
]

student/urls.py
from django.urls import path
from .views import (
    index, project_detail, new_student_project, add_project_image, UpdateProjectView, DeleteProjectView, add_project_image, my_projects, connect_with_user
)


app_name = 'student'


urlpatterns = [
    path('connect/<int:user_pk>', connect_with_user, name='connect_with_user'),
    path('projects/<int:student_pk>', my_projects, name='my_projects'),
    path('add/project/image/<int:project_pk>', add_project_image, name='add_project_image'),
    path('delete/project/<int:pk>', DeleteProjectView.as_view(), name='delete_project'),
    path('update/project/<pk>', UpdateProjectView.as_view(), name='update_project'),
    path('add/project/image/<int:project_pk>', add_project_image, name='add_project_image'),
    path('', index, name='index'),
    path('new/student/project', new_student_project, name='new_student_project'),
    path('project/<int:project_pk>', project_detail, name='project_detail'),
]

student/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model
from accounts.models import Student
from taggit.managers import TaggableManager
from hitcount.models import HitCountMixin
from hitcount.settings import MODEL_HITCOUNT
from django.contrib.contenttypes.fields import GenericRelation
User = get_user_model()

class ProjectImage(models.Model):
    image = models.ImageField(upload_to='student/%Y/%m/%d', null=True, blank=True)

class StudentProject(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='student/%Y/%m/%d', null=True, blank=True)
    images = models.ManyToManyField(ProjectImage, related_name='project_images')
    intro = models.CharField(max_length=100, default='')
    description = models.TextField()
    owner = models.ForeignKey(Student, on_delete=models.CASCADE, null=True, related_name='student_projects')
    tags = TaggableManager()
    hit_count_generic = GenericRelation(
        MODEL_HITCOUNT, object_id_field='object_pk', related_query_name='hit_count_relation')
    created = models.DateTimeField(auto_now_add=True)

    

    def __str__(self):
        return 'Student Project By {}'.format(self.name)

    def get_absolute_url(self):
        return reverse('student:project_detail', kwargs={'project_pk': self.pk})

student/forms.py
from django import forms
from student.models import StudentProject, ProjectImage


class ProjectImageForm(forms.ModelForm):

    class Meta:
        model = ProjectImage
        fields = ['image' ]

class StudentProjectForm(forms.ModelForm):

    class Meta:
        model = StudentProject
        fields = ['name', 'intro', 'image', 'description', 'tags']

student/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from accounts.models import Student
from .models import (
    ProjectImage, StudentProject
)
from studio.models import Project
from .forms import (
    StudentProjectForm, ProjectImageForm
)
from blog.models import Post, Comment
from django.contrib.auth.decorators import login_required, permission_required
from django.views.generic import UpdateView, DeleteView
from django.contrib.auth import get_user_model

User = get_user_model()

def index(request):
    username = request.user.username
    student = get_object_or_404(Student, username=username)
    student_projects = StudentProject.objects.all()
    posts = Post.objects.order_by('-created')[0:5]
    my_projects = student.student_projects.order_by('-name')
    other_students = Student.objects.exclude(pk=student.pk)
    my_network = student.network.all()
    return render(request, 'student/index.html', {
        'latest_projects': Project.objects.order_by('-created')[0:5],
        'posts': posts,
        'student_projects': student_projects,
        'my_projects': my_projects,
        'student': student,
        'other_students': other_students,
        'my_network': my_network
    })

@login_required
def new_student_project(request):
    if  request.user.is_student:
        username = request.user.username
        student = Student.objects.get(username=username)    
        if request.method == 'POST':
            form = StudentProjectForm(request.POST, request.FILES)
            if form.is_valid():
                project = form.save(commit=False)
                project.owner = student
                project.save()
                return redirect('student:project_detail', project.pk)
        else:
            form = StudentProjectForm()
        return render(request, 'student/forms/project_form.html', {
            'form': form,
            'form_header': 'Create A New Project'

        })
    else: 
        return redirect('accounts:profile')
    

def project_detail(request, project_pk):
    project = get_object_or_404(StudentProject, pk=project_pk)
    return render(request, 'student/project_detail.html', {
        'project': project
    })

def add_project_image(request, project_pk):
    project = get_object_or_404(StudentProject, pk=project_pk)
    if request.method == 'POST': 
        form = ProjectImageForm(request.POST, request.FILES)
        if form.is_valid():
            if request.user.is_student:
                image = form.save()
                project.project_images.add(image)
                return redirect('student:project_detail', project.pk)
            else:
                return redirect('home:index')
    else:
        form = ProjectImageForm()
    return render('student/forms/project_image_form.html', {
        'form': form,
        'project': project
    })

class UpdateProjectView(UpdateView):
    model = StudentProject
    template_name = 'student/forms/studentproject_update_form.html'
    success_url = '/student'
    fields = ['name', 'intro', 'description', 'image', 'tags']



class DeleteProjectView(DeleteView):
    model = StudentProject
    success_url = reverse_lazy('student:index')
    template_name = 'student/forms/project_confirm_delete.html'

def add_project_image(request, project_pk):
    project = get_object_or_404(StudentProject, pk=project_pk)
    if request.method == 'POST':
        form = ProjectImageForm(request.POST, request.FILES)
        if form.is_valid():
            image = image = form.save(commit=False)
            image.project = project
            image.save()
            project.images.add(image)
            return redirect('student:project_detail', project.pk)
    else:
        form = ProjectImageForm()
    return render(request, 'student/forms/project_image_form.html', {
        'project': project,
        'form': form
    })

def my_projects(request, student_pk):
    student = get_object_or_404(Student, pk=student_pk)
    my_projects = student.student_projects.order_by('-created')
    return render(request, 'student/my_projects.html', {
        'my_projects': my_projects,
        'student': student
    })

def connect_with_user(request, user_pk):
    this_username = request.user.username
    this_student = get_object_or_404(Student, username=this_username)
    other_student = get_object_or_404(User, pk=user_pk)
    this_student.network.add(other_student)
    return redirect('student:index')
    
    

student/templates/student/index.html
{% extends 'student/header.html' %}
{% load static %}
{% load hitcount_tags %}


{% block title %}

{% if request.user.is_student %}
    {{request.user.get_full_name}}: Student
{% endif %}
        
{% endblock title %}





{% block content %}

<head>

</head>

<!-- Blog Posts -->

<div class="row">
    <div class="col-md-6 col-xl-4 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <div class="d-flex flex-row justify-content-between">


                    <h4 class="card-title">{{posts.count}} Latest Post{{posts.count|pluralize}}</h4>
                    <p class="text-muted mb-1 small"><a class="btn btn-outline-light text-highlight" href="{% url 'blog:posts' %}">View all</a></p>
                </div>
                <div class="preview-list">

                    {% for post in posts %}
                    <div class="preview-item border-bottom">
                        <div class="preview-thumbnail">

                            {% if post.image %}
                            <a href="{{post.get_absolute_url}}">
                                <img src="{{post.image.url}}" alt="image" class="rounded-circle" />
                            </a>
                            
                            {% endif %}

                        </div>
                        <div class="preview-item-content d-flex flex-grow">
                            <div class="flex-grow">
                                <div class="d-flex d-md-block d-xl-flex justify-content-between">
                                    <h6 class="preview-subject text-muted">{{post.author.get_full_name}}</h6>
                                    <p class="text-highlight">{{post.heading}}</p>
                                </div>
                                <p class="text-muted text-small">{{post.created}}</p>
                            </div>
                        </div>
                    </div>
                    {% endfor %}

                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-xl-4 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                {% if student_projects is not None %}
                <h2 class="btn btn-outline-light">Student Projects</h2>
                {% endif %}
                <div class="owl-carousel owl-theme full-width owl-carousel-dash portfolio-carousel"
                    id="owl-carousel-basic">
                    {% for project in student_projects %}
                        
                    
                    <div class="item">
                        <h4>{{project.name}}: {{project.owner.get_full_name}}</h4>
                        {% if project.image %}
                        <a href="{{project.get_absolute_url}}">
                            <img style="height: 300px; width: 80%;" src="{{project.image.url}}" alt="">
                            <span class="text-capitalize  badge badge-outline-light">See More</span>
                        </a>
                      
                        
                        {% endif %}
                    </div>
                   

                    {% endfor %}

                </div>
      
            </div>
        </div>
    </div>
    <div class="col-md-12 col-xl-4 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                
                {% if my_projects %}                    
                <h4 class="card-title">My Projects <span><a class="btn btn-outline-success" href="{% url 'student:new_student_project' %}">Start New Project</a></span></h4>
                
                <div class="wrapper">
                    {% for project in my_projects %}
                    <div class="container">
                        <h6><a class="btn btn-outline-light" href="{% url 'student:my_projects' student.pk %}">{{project.name}}</a></h6>
                    
                        {% if project.image %}
                        <img class="card-img" src="{{project.image.url}}" alt="">
                        {% endif %}
                    
                    </div>
                    
                    {% endfor %}
                </div>
                
                    
                {% endif %}
            </div>
        </div>
    </div>
</div>

<!-- Latest Projects On ADM -->
<div class="row">

    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <div class="d-flex flex-row justify-content-between">
                    <h4 class="card-title mb-1 text-center">Latest Projects On ADM</h4>
                    <p class="text-muted mb-1">Status</p>
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="preview-list">

                            {% for project in latest_projects %}
                            <div class="preview-item border-bottom">
                                <div class="preview-thumbnail">
                                    <div class="preview-icon bg-primary">

                                        {% if project.image %}
                                        <img src="{{project.image.url}}" alt="">
                                        {% endif %}

                                    </div>
                                </div>
                                <div class="preview-item-content d-sm-flex flex-grow">
                                    <div class="flex-grow">
                                        <h6 class="preview-subject"><a class="btn btn-outline-light"
                                                href="{{project.get_absolute_url}}">{{project.name}}</a></h6>
                                        <p class="text-muted mb-0">{{project.owner.get_full_name}}</p>
                                    </div>
                                    <div class="mr-auto text-sm-right pt-2 pt-sm-0">
                                        <p class="text-muted">{{project.created}}</p>
                                        <p class="text-muted mb-0">{% get_hit_count for project %} Views</p>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Latest Projects -->
<!-- NetWork -->
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Network</h4>
                <div class="row">

                    <div class="col-12">
                        <div class="container">

                            {% if other_students %}
                            <h4>Other Students</h4>
                            <div class="wrapper">

                            </div>
                            {% for student in other_students %}
                            <div class="container">
                                <h4><a class="btn btn-outline-light" href="">{{student.get_full_name}}</a> </h4>

                                {% if student.photo %}
                                <img class="card-img" src="{{student.photo.url}}" alt="">
                                {% endif %}
                                <h6>{{student.institution}}</h6>
                                <h6><a class="btn btn-outline-light" href="{% url 'student:connect_with_user' student.pk %}">Connect</a></h6>
                                <a class="badge badge-outline-danger"
                                    href="{% url 'student:my_projects' student.pk %}">{{student.first_name}}`s
                                    Projects</a>

                            </div>

                            {% endfor %}

                            {% endif %}

                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    
        <div class="col-12">
        
            {% if my_network %}
            <div class="card">
                <h2 class="card-title center">
                    My Network <span>{{my_network.count}} Person{{my_network.count|pluralize}}</span>
                </h2>
                <div class="wrapper">
        
                    {% for user in my_network %}
                    <div class="container">
                        {% if user.photo %}
                        <img class="card-img" src="{{user.photo.url}}" alt="">
                        {% endif %}
        
        
                        {% if user.is_student %}
                        <div class="container">
                            <h4>Student</h4>
                            <h5>{{user.get_full_name}}</h5>
                            <a class="badge badge-outline-light" href="{% url 'student:my_projects' user.pk %}">More about {{user.first_name}}</a>
                        </div>
                        {% endif %}
                    </div>
        
        
        
                    {% endfor %}
        
                </div>
            </div>
        
            {% endif %}
        
        </div>
  
</div>

<!-- End Network -->

{% endblock content %}



{% block javascript %}

{% endblock javascript %}

    

student/templates/student/my_projects.html
{% extends 'student/header.html' %}
{% load static %}
{% load hitcount_tags %}



{% block title %}

{% endblock title %}


{% block content %}
<section id="my-projects" style="margin: 50px auto;">

    <h3>Projects By: <span style="font-size: 18px;">{{student.get_full_name}}</span></h3>

    <div class="container1" style="margin: 50px auto;">

        {% if my_projects %}
        <div class="wrapper">
            {% for project in my_projects %}
            <div class="project-container">
                <h6>{{project.name}}</h6>
                <h6>{% get_hit_count for project %} Views</h6>

                {% if project.image %}
                <a href="{{project.get_absolute_url}}">
                    <img class="project-image fit" src="{{project.image.url}}" alt="">
                </a>
                
                {% endif %}
               
                

            </div>

            {% endfor %}

        </div>
        {% else %}
        <h4 class="text-danger">
            {{student.get_full_name}} has not uploaded any projects.
        </h4>
        <h6>Please come back at a later time</h6>
        
        {% endif %}

    </div>

</section>
{% endblock content %}

student/templates/student/project_detail.html
{% extends 'home/header.html' %}
{% load static %}
{% load hitcount_tags %}


{% block title %}
    Project: {{project.name.title}}
{% endblock title %}


{% block content %}
    <div id="content">
        
        {% if project %}
        <div class="row">
            <div class="container">
                <h1>Student Project</h1>
            </div>
           
        </div>
        <div class="row">
            <h1 class="headline">{{project.owner.get_full_name}} <span>
                Institution: {{project.owner.institution}}
                
                {% if request.user.username == project.owner.username %}
                <div class="container">
                    <a class="btn btn-black" href="{% url 'student:update_project' project.pk %}">Update</a>
                    <a class="btn btn-light" href="{% url 'student:delete_project' project.pk %}">Delete</a>
                    <a class="btn btn-light" href="{% url 'student:add_project_image' project.pk %}">Add Image</a>

                    <p style="font-size: 14px;"><a class="btn btn-black" href="{% url 'student:connect_with_user' project.owner.pk %}">Connect With {{project.owner.first_name.title}}</a> </p>
                </div>
                    
                {% endif %}
                    
            </span></h1>
            <div class="container">
                <h2 >{{project.name.title}} : <span style="font-size: 18px; margin-left: 15px;">  {% get_hit_count for project %} Views</span> </h2>
                {% if project.image %}
                    <img style="width: 60%; height: 400px;" src="{{project.image.url}}" alt="">
                {% endif %}
                    
            </div>
        </div>

    <div class="row" style="margin-bottom: 50px;">
        <div class="container">
            <div class="headline">
                <h1>About This project</h1>
                </div>
                <p class="btn btn-black">Intro</p>
                <h3>{{project.intro}}</h3>
                <p class="btn btn-black" style="margin-top: 20px;">Description</p>
                <h4>{{project.description}}</h4>
            
        </div>
<hr>
        <div class="container">
            <h4 ><a class="btn btn-black" href="">Tags </a> 
            <span>
                <i class="fa fa-arrow-circle-o-right"></i>
                
                {% for tag in project.tags.all %}
                    <a class="btn btn-light" href="">{{tag}}</a>
                {% endfor %}
                    
            </span>
            </h4>
        </div>
    </div>
    
    {% if project.images is not None %}
    <div class="row" style="margin-top: 30px;">
    <div class="headline">
        <h1 >
            Other Images
        </h1>
    </div>
       
        <div class="project-wrapper" style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px;">
            
            {% for item in project.images.all %}
                <div class="project-container fit"  style="width: 40%; height: 200px; margin: auto;">
                    <img  src="{{item.image.url}}" alt="" class="image-container fit" style="margin-bottom: 20px;">

                </div>
            {% endfor %}
                
        </div>
    </div>
        
    {% endif %}
        

       
            
        {% endif %}
            
    </div>
{% endblock content %}
    
    

student/templates/student/project_review.html
{% extends 'home/header.html' %}
{% load static %}

{% block title %}

{{project.name}}
    
{% endblock title %}
    

    
    {% block content %}

    <div id="content">
        <div class="headline container">
            <h1>{{project.name}} <span style="font-size: 14px;">{{project.student.get_full_name}}</span></h1>
        </div>
    </div>
        
    {% endblock content %}
        