accounts/urls.py
from django.urls import path
from django.contrib.auth.views import (LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetCompleteView, PasswordResetConfirmView,)
from .views import (
    register, profile, SignInView, create_profile, user_profile, UpdateUserView, moderator_request_detail, new_moderator, connect_with_user, activate_user, deactivate_user, register_student, change_password, update_profile
)
from django.urls import reverse_lazy


app_name = 'accounts'

urlpatterns = [
    path('update/profile', update_profile, name='update_profile'),
    path('change/password', change_password, name='change_password'),
    path('register/student', register_student, name='register_student'),
    path('activate/<int:user_pk>', activate_user, name='activate_user'),
    path('deactivate/<int:user_pk>', deactivate_user, name='deactivate_user'),
    path('connect/user/<int:user_pk>', connect_with_user, name='connect_user'),
    path('new/moderator/<int:user_id>', new_moderator, name='new_moderator'),
    path('moderator/request/<int:moderator_request_pk>', moderator_request_detail, name='moderator_request_detail'),
    path('user/profile/<int:user_pk>', user_profile, name='user_profile'),
    path('create/profile/<int:user_pk>', create_profile, name='create_profile'),
    path('sign/in', SignInView.as_view(), name='signin'),
    path('register/<utype>', register, name='register'),
    path('profile', profile, name='profile'),
    path('login', LoginView.as_view(
        template_name='accounts/forms/signin_form.html'), name='login'),
    path('logout', LogoutView.as_view(
        next_page='accounts:login'), name='logout'),
    path('password/change/done', PasswordChangeDoneView.as_view(template_name='accounts/registration/password_change_done.html'), name='password_change_done'),
    path('change/password', PasswordChangeView.as_view(template_name='accounts/registration/password_change_form.html', success_url=reverse_lazy('accounts:password_change_done'), extra_context={'header': 'Change Your Password'}), name='change_password'),
    path('password/reset', PasswordResetView.as_view(template_name='accounts/registration/password_reset_form.html', email_template_name='accounts/registration/password_reset_email.html',
         subject_template_name='accounts/registration/password_reset_subject.txt', success_url=reverse_lazy('accounts:password_reset_done'), extra_context={'header': 'Reset Your Password'}, from_email='support@adm.com'), name='password_reset'),

    path('password/reset/done', PasswordResetDoneView.as_view(
        template_name='accounts/registration/password_reset_done.html'), name='password_reset_done'),

    path('password/reset/confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='accounts/registration/password_reset_confirm.html', success_url=reverse_lazy('accounts:password_reset_complete')),
         name='password_reset_confirm'),
    path('password/reset/complete', PasswordResetCompleteView.as_view(template_name='accounts/registration/password_reset_complete.html'),
         name='password_reset_complete'),
    path('update/<int:pk>', UpdateUserView.as_view (extra_context={
        'header': 'Update Your Details'
    }), name='update_user'),

]

africandesignmatters/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from fcm_django.api.rest_framework import FCMDeviceAuthorizedViewSet
from rest_framework.routers import DefaultRouter
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from blog.models import Post


info_dict= {
    "queryset": Post.objects.all(),
}



router = DefaultRouter()
router.register('devices', FCMDeviceAuthorizedViewSet)





urlpatterns = [
    path('tinymce/', include('tinymce.urls')),
    path('', include('pwa.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': {'blog': GenericSitemap(info_dict, priority=0.6)}},
         name='django.contrib.sitemaps.views.sitemap'),
    path('adm_slack/', include('adm_slack.urls')),
    path('moderator/', include('moderator.urls')),
    path('api/', include(router.urls)),
    # path("firebase-messaging-sw.js",
    #     TemplateView.as_view(
    #         template_name="firebase-messaging-sw.js",
    #         content_type="application/javascript",
    #     ),
    #     name="firebase-messaging-sw.js"
    # ),
    path('student/', include('student.urls')),
    path('orders/', include('orders.urls')),
    path('cart/', include('cart.urls')),
    path('shop/', include('shop.urls')),
    path('api/', include('api.urls')),
    path('studio/', include('studio.urls')),
    path('blog/', include('blog.urls')),
    path('payments/', include('payments.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('dashboard/', include('dashboard.urls')),
    # path('sw.js', TemplateView.as_view(template_name='sw.js', content_type='application/javascript'), name='sw.js'),
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)


handler404 = 'home.views.error_404'

api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .accounts.views import (
    UserViewset
)
from .studio.views import (
    ProjectViewset
)
from .blog.views import PostViewset

router = DefaultRouter()

router.register('posts', PostViewset, basename='posts')
router.register('projects', ProjectViewset, basename='projects')
router.register('users', UserViewset, basename='users' )

urlpatterns = [
    path('blog/', include(router.urls)),
    path('accounts/', include(router.urls)),
    path('studio/', include(router.urls)),
]

blog/urls.py
from django.urls import path
from .views import (
    posts, post_detail, new_post, post_reply
)
app_name = 'blog'



urlpatterns = [
    path('reply/<int:comment_pk>', post_reply, name='reply'),
    path('new/post', new_post, name='new_post'),
    path('posts', posts, name='posts'),
    path('post/<int:post_pk>', post_detail, name='post_detail'),
]

dashboard/urls.py
from django.urls import path
from .views import (
    index, users, user_detail, new_project_category, category_detail, review_mod_request, accept_mod_request,
    reject_mod_request, activate_user, deactivate_user,
    projects, new_main_category, main_categories, main_category_detail, publish_comment, remove_comment,
    new_post, post_detail, UpdatePostView, DeletePostView,
    remove_task, posts, post_images, publish_all_comments, ethnicity_view, gender_view, enable_paragon, slack, list_slack_channels, create_channel, enable_moderator, disable_moderator, UpdateCategoryView, categories, add_about_note, about_note_detail, new_press, press_detail, new_resource, resource_detail, UpdateResourceView, DeleteResourceView, UpdatePressView, DeletePressView, press_notes, resources

)

app_name = 'dashboard'


urlpatterns = [
    path('press/notes', press_notes, name='press_notes'),
    path('resources', resources, name='resources'),
    path('delete/press/<int:pk>', DeletePressView.as_view(), name='delete_press'),
    path('update/press/<int:pk>',
         UpdatePressView.as_view(), name='update_press'),
    path('delete/resource/<int:pk>', DeleteResourceView.as_view(), name='delete_resource'),
    path('update/resource/<int:pk>',
         UpdateResourceView.as_view(), name='update_resource'),
    path('resource/<int:resource_pk>', resource_detail, name='resource_detail'),
    path('new/resource', new_resource, name='new_resource'),
    path('press/<int:press_pk>', press_detail, name='press_detail'),
    path('new/press', new_press, name='new_press'),
    path('add/about/note', add_about_note, name='add_about_note'),
    path('about/note/<int:about_pk>', about_note_detail, name='about_note_detail'),
    path('categories', categories, name='categories'),
    path('update/category/<int:pk>',
         UpdateCategoryView.as_view(), name='update_category'),
    path('enable/moderator/<int:user_pk>',
         enable_moderator, name='enable_moderator'),
    path('disable/moderator/<int:user_pk>',
         disable_moderator, name='disable_moderator'),
    path('create/channel', create_channel, name='create_channel'),
    path('list/slack/channels', list_slack_channels, name='list_slack_channels'),
    path('slack', slack, name='slack'),
    path('enable/paragon/<int:user_pk>', enable_paragon, name='enable_paragon'),
    path('gender/view', gender_view, name='gender_view'),
    path('ethnicity/view', ethnicity_view, name='ethnicity_view'),
    path('publish/all/comments', publish_all_comments, name='publish_comments'),
    path('post/images/<int:post_pk>', post_images, name='post_images'),
    path('posts', posts, name='posts'),
    path('remove/task/<int:task_pk>', remove_task, name='remove_task'),
    path('update/<int:pk>', UpdatePostView.as_view(), name='update_post'),
    path('delete/<int:pk>', DeletePostView.as_view(), name='delete_post'),
    path('new/post', new_post, name='new_post'),
    path('post/<int:post_pk>', post_detail, name='post_detail'),
    path('publish/comment/<int:comment_pk>',
         publish_comment, name='publish_comment'),
    path('remove/comment/<int:comment_pk>',
         remove_comment, name='remove_comment'),
    path('main/categories', main_categories, name='main_categories'),
    path('new/top/category', new_main_category, name='new_main_category'),
    path('main/category/<int:topcat_pk>',
         main_category_detail, name='main_category_detail'),
    path('projects', projects, name='projects'),
    path('activate/<int:user_pk>', activate_user, name='activate_user'),
    path('deactivate/<int:user_pk>', deactivate_user, name='deactivate_user'),
    path('reject/mod/request/<int:mod_request_pk>',
         reject_mod_request, name='reject_mod_request'),
    path('accept/mod/request/<int:mod_request_pk>',
         accept_mod_request, name='accept_mod_request'),
    path('review/mod/request/<int:mod_request_pk>',
         review_mod_request, name='review_mod_request'),
    path('project/category/<int:category_pk>',
         category_detail, name='category_detail'),
    path('new/project/category/<int:topcat_pk>',
         new_project_category, name='new_project_category'),

    path('', index, name='index'),
    path('users', users, name='users'),
    path('user/<int:user_pk>', user_detail, name='user_detail'),

]

studio/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import (
    index, new_project, project_categories,
    category_detail, project_tags, designer, moderator, projects, new_category, users, user_detail, new_main_category, main_categories, main_category_detail,
    ProjectDetailView, my_projects, project_categories, my_projects, ProjectUpdateView, ProjectDelete, review_project, new_project_image, search_projects,
)

app_name = 'studio'


urlpatterns = [
    
    path('search/projects', search_projects, name='search_projects'),
    path('new/project/image/<int:project_pk>', new_project_image, name='new_project_image'),
    path('review/project/<int:project_pk>', review_project, name='review_project'),
    path('delete/project/<pk>', ProjectDelete.as_view(), name='delete_project'),
    path('update/project/<pk>', ProjectUpdateView.as_view(), name='update_project'),
    path('my/projects/<int:user_pk>', my_projects, name='my_projects'),
    path('project/categories', project_categories,name='project_categories'),
    path('my/projects/<int:user_pk>', my_projects, name='my_projects'),
    path('project/<int:pk>', ProjectDetailView.as_view(template_name='studio/project_detail.html'), name='project_detail'),
    path('main/category/<int:main_category_pk>', main_category_detail, name='main_category_detail'),
    path('main/categories', main_categories, name='main_categories'),
    path('new/main/category', new_main_category, name='new_main_category'),
    path('user/<int:user_pk>', user_detail, name='user_detail'),
    path('users', users, name='users'),
    path('new/category/<int:main_category_pk>', new_category, name='new_category'),
    path('projects', projects, name='projects'),
    path('moderator', moderator, name='moderator'),
    path('designer', designer, name='designer'),
    path('project/tags/<tag>', project_tags, name='project_tags'),
    path('category/<int:category_pk>', category_detail,name='category_detail'),
    path('categories', project_categories, name='categories'),
    # path('project/<int:project_pk>', project_detail, name='project_detail'),
    path('', index, name='index'),
    path('new/project/<int:category_pk>', new_project, name='new_project'),

    
]

studio/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.contrib.contenttypes.fields import GenericRelation
from taggit.managers import TaggableManager
from hitcount.models import HitCountMixin
from hitcount.settings import MODEL_HITCOUNT
from embed_video.fields import EmbedVideoField
User = settings.AUTH_USER_MODEL

CATEGORY_CHOICES = (
    ('Design', 'Design'),
    ('Seventh Art', 'Seventh Art'),
)

class MainCategory(models.Model):
    name = models.CharField(max_length=50, choices=CATEGORY_CHOICES, default='', unique=True)
    image = models.ImageField(upload_to='main/categories/%Y/%m/%d', null=True, blank=True)
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('studio:main_category_detail', kwargs={'main_category_pk': self.pk})


class Category(models.Model):
    main_category = models.ForeignKey(MainCategory, on_delete=models.CASCADE, null=True, related_name='categories')
    name = models.CharField(max_length=100, unique=True)
    category_info = models.TextField(default='')
    image = models.ImageField(upload_to='categories/%Y/%m/%d', null=True, blank=True)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('studio:category_detail', kwargs={'category_pk': self.pk})


class ProjectImage(models.Model):
    image = models.ImageField(
        upload_to='project/images/%Y/%m/%d', null=True, blank=True)



class Project(models.Model, HitCountMixin):
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, null=True, related_name='projects')
    name = models.CharField(max_length=100, default='', unique=True)
    location = models.CharField(max_length=100, default='')
    description = models.TextField()
    image = models.ImageField(
        upload_to='project/images/%Y/%m/%d', null=True, blank=True)
    video = EmbedVideoField(blank=True, null=True)
    owner = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, related_name='projects')
    images = models.ManyToManyField(
        ProjectImage, related_name='project_images')
    created = models.DateTimeField(auto_now_add=True)
    tags = TaggableManager()
    hit_count_generic = GenericRelation(MODEL_HITCOUNT, object_id_field='object_pk', related_query_name='hit_count_relation')    

    class Meta:
        verbose_name = 'Project'
        verbose_name_plural = 'Projects'

    def __str__(self):
        return '{}: {}'.format(self.name, self.owner.get_full_name())

    def get_absolute_url(self):
        return reverse('studio:project_detail', kwargs={'pk': self.pk})


class Review(models.Model):
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='reviews')
    project = models.ForeignKey(
        Project, on_delete=models.CASCADE, null=True, related_name='reviews')
    created = models.DateTimeField(auto_now_add=True)

studio/forms.py
from django import forms
from .models import (
     Category, ProjectImage, Project, Review, MainCategory
)

from embed_video.fields import EmbedVideoFormField

class MainCategoryForm(forms.ModelForm):

    class Meta:
        model = MainCategory
        fields = ['name']

        
class ProjectImageForm(forms.ModelForm):

    class Meta:
        model = ProjectImage
        fields = ['image']


class CategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = ['name', 'category_info', 'image']

class ProjectForm(forms.ModelForm):
    name = forms.CharField(label='Name Your Project')
    intro = forms.TextInput(attrs={
        'placeholder': 'Brief Intro To Your Project', 'rows': 10, 'cols': 15})
    video = EmbedVideoFormField(widget=forms.TextInput(attrs={'placeholder':'Enter Video URL'}), label='Embed Video')
    description = forms.TextInput(attrs={'placeholder': 'Describe Your project'})
    

    class Meta:
        model = Project
        exclude = ['owner', 'created', 'images', 'category']


class ReviewForm(forms.ModelForm):
    content = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Review this project'}), label='Add a review')
    class Meta:
        model = Review
        fields = ['content']

api/studio/views.py
from rest_framework.viewsets import ModelViewSet
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from .serializers import ProjectSerializer
from studio.models import (
    MainCategory, Category, Project
)

class ProjectViewset(ModelViewSet):
    permission_classes = [IsAuthenticatedOrReadOnly]
    serializer_class = ProjectSerializer
    queryset = Project.objects.order_by('-created')


    

studio/templates/studio/category_detail.html
{% extends 'home/header.html' %}
{% load static %}



{% block title %}
    {{category.name}}
{% endblock title %}



{% block content %}
<head>
    <style>
        .project-container{
            width: 80%;
            height: 400px;
            margin: auto;
            text-align: center;
        }
      .project-img{
          height: 60%;
          width: 60%;
          object-fit: contain;
      }
    </style>
    
</head>


<div id="content">
<div id="category" class="row" >
    <div class="span12">
        <div class="container" data-aos="fade-up" data-aos-duration="1000">
            <h1 class="center text-muted">{{category.name}} <span style="padding-top: 20px; display: block;"><a
                        class="btn btn-black text-muted" href="{% url 'studio:new_project' category.pk %}">Create A New
                        Project</a></span><span>{% if category.image %}
                    <img class="project-image" src="{{category.image.url}}" alt="">
                    {% endif %}</span></h1>
        
            {% if category.category_info %}
            <div class="accordion" >
                <a class="accordion-item" style="color: #eee;" href="">Info</a>
                <div class="accordion-item-content">
                    <p style="color: #eee;">
                        {{category.category_info}}
                    </p>
                    
                </div>
            </div>
            {% endif %}
        
        </div>
        
        
        <hr>
        {% if category.projects.count > 0 %}
        <div class="wrapper">
        
            {% for project in category.projects.all %}
            <div class="project-container ">
                
                {% if project.image %}
               <a href="{{project.get_absolute_url}}"><img class="project-img" src="{{project.image.url}}" alt=""></a>
                {% endif %}
                <h5 class="center">{{project.owner.get_full_name}}</h5>
              
        
            </div>
            {% endfor %}
        
        
        
        </div>
        
        {% else %}
        <div class="container">
            <h4>Sorry. There are no projects in <strong>{{category.name}}</strong>
        
            </h4>
            <p>Please come back later to see updates. Thanks</p>
        
            <h6 ><i class="fa fa-arrow-circle-down"> </i>Check Other Disciplines Below<i
                    class="fa fa-arrow-circle-down"> </i></h6>
        </div>
        
        {% endif %}


    </div>
    
</div>



<section id="other-categories" style="margin: 100px auto;">
    <div class="container headline" data-aos="zoom-in" data-aos-duration="1000">
        <div class="headline">
            <h1>
                Other Categories
            </h1>
        </div>
        
        <hr>
        <div style="display: block;">
            {% for cat in other_categories %} 
                <a style="margin: 0 0 0.5px 0.5px;" class="btn btn-black " href="{{cat.get_absolute_url}}" >{{cat.name}}</a>
           
            {% endfor %}
        </div>
       
    </div>
</section>
</div>



{% endblock content %}


{% block javascript %}

<script>
    $(function () {
            $(".accordion .accordion-item").removeClass('active').next("div").slideUp("slow");

        })
</script>
    
{% endblock javascript %}
    
    

studio/templates/studio/index.html
{% extends 'studio/header.html' %}
{% load static %}
{% load hitcount_tags %}
{% load crispy_forms_tags %}

{% block title %}
    
{% endblock title %}


{% block content %}

<!-- My projects -->
<div class="row">
    <div class="col-md-6 col-xl-4 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <div class="d-flex flex-row justify-content-between">

                    <h4 class="card-title">My Projects: {{request.user.projects.count}} Project{{request.user.projects.count|pluralize}}</h4>
                   
                    <p class="text-muted mb-1 small"><a class="badge badge-outline-success text-highlight"
                            href="{% url 'studio:my_projects' request.user.pk %}">See More</a></p>
                </div>
                <div class="preview-list">

                    {% for project in request.user.projects.all %}
                    <div class="preview-item border-bottom">
                        <div class="preview-thumbnail">

                            {% if project.image %}
                            <img src="{{project.image.url}}" alt="image" class="rounded-circle" />
                            {% endif %}

                        </div>
                        <div class="preview-item-content d-flex flex-grow">
                            <div class="flex-grow">
                                <div class="d-flex d-md-block d-xl-flex justify-content-between">
                                    <h6 class="preview-subject">Created On: {{project.created}}</h6>
                                  
                                </div>
                                <p class="text-muted"><a href="{% url 'studio:my_projects' request.user.pk %}">Review</a></p>
                            </div>
                        </div>
                    </div>
                    {% endfor %}

                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-xl-4 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Projects</h4>
                <div class="owl-carousel owl-theme full-width owl-carousel-dash portfolio-carousel"
                    id="owl-carousel-basic">

                    {% for project in latest_projects %}

                    {% if project.image %}
                    <div class="item">
                        <a href="{{project.get_absolute_url}}">
                            <img style="height: 300px; width: 80%;" src="{{project.image.url}}" alt="">
                            <span class="text-capitalize  btn btn-white">View</span>
                        </a>

                    </div>
                    {% endif %}

                    {% endfor %}

                </div>

            </div>
        </div>
    </div>

</div>

<!-- End My projects -->

<!-- Blog Posts -->
<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <div class="d-flex flex-row justify-content-between">


                    <h4 class="card-title">{{posts.count}} Latest Post{{posts.count|pluralize}}</h4>
                    <p class="text-muted mb-1 small"><a class="badge badge-outline-success text-highlight"
                            href="{% url 'blog:posts' %}">View all</a></p>
                </div>
                <div class="preview-list">

                    {% for post in posts %}
                    <div class="preview-item border-bottom">
                        <div class="preview-thumbnail">

                            {% if post.image %}
                            <img src="{{post.image.url}}" alt="image" class="rounded-circle" />
                            {% endif %}

                        </div>
                        <div class="preview-item-content d-flex flex-grow">
                            <div class="flex-grow">
                                <div class="d-flex d-md-block d-xl-flex justify-content-between">
                                    <h6 class="preview-subject">{{post.author.first_name}}</h6>
                                    <p class="text-muted text-small">{{post.created}}</p>
                                </div>
                                <p class="text-muted">{{post.heading}}</p>
                            </div>
                        </div>
                    </div>
                    {% endfor %}

                </div>
            </div>
        </div>
    </div>
  
    
</div>
<!-- End Blog Posts -->
<!-- Latest Projects -->
<div class="row">

    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <div class="d-flex flex-row justify-content-between">
                    <h4 class="card-title mb-1">Latest Projects</h4>
                    <p class="text-muted mb-1">Status</p>
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="preview-list">

                            {% for project in latest_projects %}
                            <a class="text-light" href="{{project.get_absolute_url}}">
                                <div class="preview-item border-bottom">
                                    <div class="preview-thumbnail">
                                        <div class="preview-icon bg-primary">

                                            {% if project.image %}
                                            <img src="{{project.image.url}}" alt="">
                                            {% endif %}

                                        </div>
                                    </div>
                                    <div class="preview-item-content d-sm-flex flex-grow">
                                        <div class="flex-grow">
                                            <h6 class="preview-subject"><a class="btn btn-outline-light" href="{{project.get_absolute_url}}">{{project.name}}</a></h6>
                                            <p class="text-muted mb-0">{{project.owner.get_full_name}}</p>
                                        </div>
                                        <div class="mr-auto text-sm-right pt-2 pt-sm-0">
                                            <p class="text-muted">{{project.created}}</p>
                                            <p class="text-muted mb-0">{% get_hit_count for project %} Views</p>
                                        </div>
                                    </div>
                                </div>
                            </a>

                            {% endfor %}


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Latest Projects -->

<!-- Tasks -->
<div class="row">
    
    <div class="col-md-12 col-xl-4 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Tasks</h4>
                <div class=" d-flex ">
                    <form action="" method="POST" style="color: #fff;">
                        {% csrf_token %}
                        <div class="form-inline">
                            {{task_form|crispy}}
                            {{form.media}}
                        </div>
    
                        <button type="submit" class="badge badge-success mt-2" style="display: block;">Add</button>
    
    
                    </form>
    
    
                </div>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Task</th>
                                <th>Due Date</th>
                                <th>Action</th>
                                <th>Task Id</th>
                            </tr>
                        <tbody>
    
                            {% for item in tasks %}
                            <tr>
                                <td>{{item.new_task}}</td>
                                <td>{{item.due_date}}</td>
                                <td><a id="cancel-task" href=""><i class="fa fa-remove"></i></a></td>
                                <td id="task-id"><a class="badge badge-outline-danger"
                                        href="{% url 'dashboard:remove_task' item.pk %}">Remove</a></td>
                            </tr>
                            {% endfor %}
    
                        </tbody>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Tasks -->

    
{% endblock content %}
    
    

studio/templates/studio/my_projects.html
{% extends 'studio/header.html' %}
{% load static %}
{% load hitcount_tags %}



{% block title %}

{% endblock title %}


{% block content %}
<section id="my-projects" style="margin: 50px auto;">

    <h3>Projects By: <span style="font-size: 18px;">{{user.get_full_name}}</span></h3>

    <div class="container1" style="margin: 50px auto;">

        {% if my_projects %}
        <div class="wrapper">
            {% for project in my_projects %}
            <div class="project-container">
                <h6>{{project.name}}</h6>
                <h6>{% get_hit_count for project %} Views</h6>

                {% if project.image %}
                <a href="{{project.get_absolute_url}}">
                    <img class="project-image fit" style="width: 80%; height: 80%;" src="{{project.image.url}}" alt="">
                </a>
                
                {% endif %}
                <h6><a class="badge badge-outline-success" href="{% url 'studio:update_project' project.pk %}">Update</a> <span><a class="badge badge-outline-danger" href="{% url 'studio:delete_project' project.pk %}">Delete</a></span></h6>
                <h6><a class="badge badge-outline-warning" href="{% url 'studio:new_project_image' project.pk %}">Add Images</a></h6>

            </div>

            {% endfor %}

        </div>
        {% else %}
        <h4 class="text-danger">
            You have not uploaded projects yet.
        </h4>
        <h6><a class="btn btn-outline-danger" href="{% url 'studio:categories' %}">Create a project</a> </h6>
        {% endif %}

    </div>

</section>
{% endblock content %}