africandesignmatters/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from fcm_django.api.rest_framework import FCMDeviceAuthorizedViewSet
from rest_framework.routers import DefaultRouter
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from blog.models import Post


info_dict= {
    "queryset": Post.objects.all(),
}



router = DefaultRouter()
router.register('devices', FCMDeviceAuthorizedViewSet)





urlpatterns = [
    path('tinymce/', include('tinymce.urls')),
    path('', include('pwa.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': {'blog': GenericSitemap(info_dict, priority=0.6)}},
         name='django.contrib.sitemaps.views.sitemap'),
    path('adm_slack/', include('adm_slack.urls')),
    path('moderator/', include('moderator.urls')),
    path('api/', include(router.urls)),
    # path("firebase-messaging-sw.js",
    #     TemplateView.as_view(
    #         template_name="firebase-messaging-sw.js",
    #         content_type="application/javascript",
    #     ),
    #     name="firebase-messaging-sw.js"
    # ),
    path('student/', include('student.urls')),
    path('orders/', include('orders.urls')),
    path('cart/', include('cart.urls')),
    path('shop/', include('shop.urls')),
    path('api/', include('api.urls')),
    path('studio/', include('studio.urls')),
    path('blog/', include('blog.urls')),
    path('payments/', include('payments.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('dashboard/', include('dashboard.urls')),
    # path('sw.js', TemplateView.as_view(template_name='sw.js', content_type='application/javascript'), name='sw.js'),
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)


handler404 = 'home.views.error_404'

api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .accounts.views import (
    UserViewset
)
from .studio.views import (
    ProjectViewset
)
from .blog.views import PostViewset

router = DefaultRouter()

router.register('posts', PostViewset, basename='posts')
router.register('projects', ProjectViewset, basename='projects')
router.register('users', UserViewset, basename='users' )

urlpatterns = [
    path('blog/', include(router.urls)),
    path('accounts/', include(router.urls)),
    path('studio/', include(router.urls)),
]

dashboard/urls.py
from django.urls import path
from .views import (
    index, users, user_detail, new_project_category, category_detail, review_mod_request, accept_mod_request,
    reject_mod_request, activate_user, deactivate_user,
    projects, new_main_category, main_categories, main_category_detail, publish_comment, remove_comment,
    new_post, post_detail, UpdatePostView, DeletePostView,
    remove_task, posts, post_images, publish_all_comments, ethnicity_view, gender_view, enable_paragon, slack, list_slack_channels, create_channel, enable_moderator, disable_moderator, UpdateCategoryView, categories, add_about_note, about_note_detail, new_press, press_detail, new_resource, resource_detail, UpdateResourceView, DeleteResourceView, UpdatePressView, DeletePressView, press_notes, resources

)

app_name = 'dashboard'


urlpatterns = [
    path('press/notes', press_notes, name='press_notes'),
    path('resources', resources, name='resources'),
    path('delete/press/<int:pk>', DeletePressView.as_view(), name='delete_press'),
    path('update/press/<int:pk>',
         UpdatePressView.as_view(), name='update_press'),
    path('delete/resource/<int:pk>', DeleteResourceView.as_view(), name='delete_resource'),
    path('update/resource/<int:pk>',
         UpdateResourceView.as_view(), name='update_resource'),
    path('resource/<int:resource_pk>', resource_detail, name='resource_detail'),
    path('new/resource', new_resource, name='new_resource'),
    path('press/<int:press_pk>', press_detail, name='press_detail'),
    path('new/press', new_press, name='new_press'),
    path('add/about/note', add_about_note, name='add_about_note'),
    path('about/note/<int:about_pk>', about_note_detail, name='about_note_detail'),
    path('categories', categories, name='categories'),
    path('update/category/<int:pk>',
         UpdateCategoryView.as_view(), name='update_category'),
    path('enable/moderator/<int:user_pk>',
         enable_moderator, name='enable_moderator'),
    path('disable/moderator/<int:user_pk>',
         disable_moderator, name='disable_moderator'),
    path('create/channel', create_channel, name='create_channel'),
    path('list/slack/channels', list_slack_channels, name='list_slack_channels'),
    path('slack', slack, name='slack'),
    path('enable/paragon/<int:user_pk>', enable_paragon, name='enable_paragon'),
    path('gender/view', gender_view, name='gender_view'),
    path('ethnicity/view', ethnicity_view, name='ethnicity_view'),
    path('publish/all/comments', publish_all_comments, name='publish_comments'),
    path('post/images/<int:post_pk>', post_images, name='post_images'),
    path('posts', posts, name='posts'),
    path('remove/task/<int:task_pk>', remove_task, name='remove_task'),
    path('update/<int:pk>', UpdatePostView.as_view(), name='update_post'),
    path('delete/<int:pk>', DeletePostView.as_view(), name='delete_post'),
    path('new/post', new_post, name='new_post'),
    path('post/<int:post_pk>', post_detail, name='post_detail'),
    path('publish/comment/<int:comment_pk>',
         publish_comment, name='publish_comment'),
    path('remove/comment/<int:comment_pk>',
         remove_comment, name='remove_comment'),
    path('main/categories', main_categories, name='main_categories'),
    path('new/top/category', new_main_category, name='new_main_category'),
    path('main/category/<int:topcat_pk>',
         main_category_detail, name='main_category_detail'),
    path('projects', projects, name='projects'),
    path('activate/<int:user_pk>', activate_user, name='activate_user'),
    path('deactivate/<int:user_pk>', deactivate_user, name='deactivate_user'),
    path('reject/mod/request/<int:mod_request_pk>',
         reject_mod_request, name='reject_mod_request'),
    path('accept/mod/request/<int:mod_request_pk>',
         accept_mod_request, name='accept_mod_request'),
    path('review/mod/request/<int:mod_request_pk>',
         review_mod_request, name='review_mod_request'),
    path('project/category/<int:category_pk>',
         category_detail, name='category_detail'),
    path('new/project/category/<int:topcat_pk>',
         new_project_category, name='new_project_category'),

    path('', index, name='index'),
    path('users', users, name='users'),
    path('user/<int:user_pk>', user_detail, name='user_detail'),

]

dashboard/forms.py
from django import forms
from .models import PostImage, PressNote
from home.models import AboutImage, AboutNote, Resource



class PressNoteForm(forms.ModelForm):
    
    class Meta:
        model = PressNote
        fields = '__all__'

class AboutNoteForm(forms.ModelForm):
    # images = forms.ImageField(required=False)
    
    class Meta:
        model = AboutNote
        exclude = ['created', 'images']


class AboutImageForm(forms.ModelForm):

    class Meta:
        model = AboutImage
        fields = ['image']


class ResourceForm(forms.ModelForm):

    class Meta:
        model = Resource
        fields = ['content']

dashboard/views.py
from django.utils.safestring import SafeString
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin
from accounts.models import (
    ModeratorRequest, Profile, Task
)
from accounts.forms import TaskForm
from blog.models import (
    Post, PostImage, Comment, PostReply
)
from blog.forms import (
    PostForm, PostImageForm, PostReplyForm, CommentForm
)
from .tasks import caution_comment_author
from student.models import StudentProject

from studio.models import (
    Category, Project, ProjectImage, MainCategory,
)

from studio.forms import (
    CategoryForm, ProjectForm, ProjectImageForm, MainCategoryForm,

)
from orders.models import (
    Order, OrderItem
)

from shop.models import (
    Product, ProductCategory
)
from home.models import AboutImage, AboutNote, Resource
from .forms import (
    AboutImageForm, AboutNoteForm, PressNoteForm, ResourceForm
)
from django.db.models import (
    Sum, Max, Avg, Count, Aggregate
)
from django.views.generic import (
    UpdateView, DeleteView
)
from django.urls import reverse_lazy
from django.http import HttpResponse, JsonResponse
from django.conf import settings
from adm_slack.models import SlackChannel
User = get_user_model()

slack_token = settings.SLACK_AUTH_TOKEN 
slack_client_id = settings.SLACK_CLIENT_ID
import requests
import os
import logging
from time import time
from slack_sdk import WebClient
from adm_slack.models import SlackChannel
from adm_slack.forms import SlackChannelForm
from django.core.paginator import Paginator
from .models import PressNote


def new_press(request):
    if request.method == 'POST':
        form = PressNoteForm(request.POST,  request.FILES)
        if form.is_valid():
            press = form.save()
            return redirect('dashboard:press_detail',press.pk)
    else:
        form = PressNoteForm()
    return render(request, 'dashboard/forms/press_note_form.html', {
        'form': form
    }) 
    
def press_detail(request, press_pk):
    press = get_object_or_404(PressNote, pk=press_pk)
    return render(request, 'dashboard/press_detail.html', {
        'press': press
    })

# Resource


def new_resource(request):
    if request.method == 'POST':
        form = ResourceForm(request.POST,request.FILES)
        if form.is_valid():
            resource = form.save()
            return redirect('dashboard:resource_detail', resource.pk)
    else:
        form = ResourceForm()
    return render(request, 'dashboard/forms/resource_form.html', {
        'form': form
    })


def resource_detail(request, resource_pk):
    resource = get_object_or_404(Resource, pk=resource_pk)
    return render(request, 'dashboard/resource_detail.html', {
        'resource': resource
    })

class UpdateResourceView(LoginRequiredMixin, UpdateView):
    model = Resource
    template_name = 'dashboard/forms/resource_update_form.html'
    fields = ['content']
    
    def get_success_url(self, *args, **kwargs):
        pk = self.kwargs['pk']
        resource = get_object_or_404(Resource, pk=pk)
        return reverse_lazy('dashboard:resource_detail', kwargs={'resource_pk': pk})

class DeleteResourceView(LoginRequiredMixin, DeleteView):
    model = Resource
    success_url = '/dashboard/index'


class UpdatePressView(LoginRequiredMixin, UpdateView):
    model = PressNote
    template_name = 'dashboard/forms/press_update_form.html'
    fields = ['content']

    def get_success_url(self, *args, **kwargs):
        pk = self.kwargs['pk']
        press = get_object_or_404(Press, pk=pk)
        return reverse_lazy('dashboard:press_detail', kwargs={'press_pk': pk})


class DeletePressView(LoginRequiredMixin, DeleteView):
    model = PressNote
    success_url = '/dashboard/index'




def admin_pass(user):
    if user.is_superuser:
        return True
    else: 
        return False

@login_required(login_url='/accounts/login')
@user_passes_test(admin_pass)
def index(request):
    press_notes = PressNote.objects.all()
    resources = Resource.objects.all()
    # add_to_slack = "https://slack.com/oauth/authorize?scope=bot&client_id={}".format(
    #     slack_client_id)
    # client = WebClient(token=slack_token)
    # response = client.conversations_list()
    # slack_channels = response['channels']
    sold_list = []
    sold_data = {}
    products_sold = OrderItem.objects.values(
        'product__name').annotate(Max('quantity'))
    for i in products_sold:
        sold_data['product'] = i['product__name']
        sold_data['quantity'] = i['quantity__max']
        sold_list.append(sold_data)
    users = User.objects.all()
    projects = Project.objects.all()
    student_projects = StudentProject.objects.order_by('-created')
    moderators = User.objects.filter(is_moderator=True)
    posts = Post.objects.all()
    students = User.objects.filter(is_student=True)
    studios = User.objects.filter(is_designer=True)
    latest_projects = Project.objects.order_by('-created')[0:5]
    orders = Order.objects.order_by('-created')
    mod_requests = ModeratorRequest.objects.filter(accepted=False)
    blog_comments = Comment.objects.select_related(
        'post').order_by('-created')[0:9]
    products = Product.objects.all()
    product_categories = ProductCategory.objects.all()
    if request.method == 'POST':
        form = TaskForm(request.POST, request.FILES)
        if form.is_valid():
            task = form.save(commit=False)
            task.user = request.user
            task.save()
            return redirect('accounts:profile')
    else:
        form = TaskForm()
    return render(request, 'dashboard/index.html',
                  {
                      'product_categories': product_categories,
                      'mod_requests': mod_requests,
                      'blog_comments': blog_comments,
                      'users': users,
                      'projects': projects,
                      'moderators': moderators,
                      'posts': posts,
                      'students': students,
                      'student_projects': student_projects,
                      'studios': studios,
                      'latest_projects': latest_projects,
                      'orders': orders,
                      'order_items': OrderItem.objects.order_by('-created'),
                      'products': products,
                      'sold_list': sold_list[0:2],
                      'task_form': form,
                      'tasks': Task.objects.order_by('due_date').filter(completed=False, user=request.user),
                      'press_notes': press_notes,
                      'resources': resources
                    #   'slack_btn': add_to_slack,
                    #   'slack_channels': slack_channels,
                    
                  })

def resources(request):
    resources = Resource.objects.all()
    return render(request, 'dashboard/resources.html', {
        'resources': resources
    })


def press_notes(request):
    press_notes = PressNote.objects.all()
    return render(request, 'dashboard/press_notes.html', {
        'press_notes': press_notes
    })


def ethnicity_view(request):
    e_data = []
    e_labels = []
    ethnicity_queryset = User.objects.values('ethnicity').exclude(ethnicity__exact='').annotate(e_count=Count('ethnicity'))
    for i in ethnicity_queryset:
        e_data.append(i['e_count'])
        e_labels.append(i['ethnicity'])
    return JsonResponse(data={'data':e_data, 'labels':e_labels})

def gender_view(request):
    gender_labels = []
    gender_data = []
    gender_queryset = User.objects.values('gender').exclude(gender__exact='').annotate(gender_count=Count('gender'))
    for i in gender_queryset:
        gender_labels.append(i['gender'])
        gender_data.append(i['gender_count'])
    return JsonResponse(data={'data': gender_data, 'labels': gender_labels})


@login_required(login_url='/accounts/login')
@user_passes_test(admin_pass)
def users(request):
    users = User.objects.order_by('-last_name')
    return render(request, 'dashboard/users.html', {
        'users': users
    })


@login_required(login_url='/accounts/login')
@user_passes_test(admin_pass)
def user_detail(request, user_pk):
    user = get_object_or_404(User, pk=user_pk)
    return render(request, 'dashboard/user_detail.html', {'user': user})


@login_required(login_url='/accounts/login')
@user_passes_test(admin_pass)
def new_project_category(request, topcat_pk):
    main_category = get_object_or_404(MainCategory, pk=topcat_pk)
    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES)
        if form.is_valid():
            category = form.save(commit=False)
            category.main_category = main_category
            category.save()
            return redirect('dashboard:category_detail', category.pk)
    else:
        form = CategoryForm()
    return render(request, 'dashboard/forms/project_category_form.html', {
        'form': form
    })


@login_required(login_url='/accounts/login')
@user_passes_test(admin_pass)
def category_detail(request, category_pk):
    category = get_object_or_404(Category, pk=category_pk)
    return render(request, 'dashboard/category_detail.html', {
        'category': category
    })


@login_required(login_url='/accounts/login')
@user_passes_test(admin_pass)
def review_mod_request(request, mod_request_pk):
    mod_request = get_object_or_404(ModeratorRequest, pk=mod_request_pk)
    return render(request, 'dashboard/review_mod_request.html', {
        'mod_request': mod_request
    })


@login_required(login_url='/accounts/login')
@user_passes_test(admin_pass)
def accept_mod_request(request, mod_request_pk):
    mod_request = get_object_or_404(ModeratorRequest, pk=mod_request_pk)
    user = mod_request.user

dashboard/templates/dashboard/about_note_detail.html
{% extends 'dashboard/header.html' %}
{% load static %}


{% block title %}
{{about_note.title}} {{about_note.created}}
{% endblock title %}



{% block content %}

<head>
    <style>

    </style>
</head>
<div class="row col-12 pt-5" style="margin: 100px auto;">

    {% if about_note %}

    <div class=" container" style="background-color: #000;">
        <h2>{{about_note.title}} <span>
        <blockquote>{{about_note.created}}</blockquote>
            </span></h2>
        {% if about_note.image %}
        <img class="card-img" src="{{about_note.image.url}}" alt="">

        {% endif %}

    </div>


    <div class="container">
        <h4>{{about_note.body|safe}}</h4>
    </div>
    <div class="container" style="margin-top: 80px;display: flex; margin-left: 10px;">
        <h4><a class="badge badge-outline-light" href=" ">Add Images</a></h4>
        <h5><a class="badge badge-outline-success" href="">Update</a><span><a
                    class="badge badge-outline-danger"
                    href="">Delete</a></span></h5>
    </div>


    {% if about_note.images %}

    <div class="row">


        <div class=" span12  mt-5">
            <h2 class="center"> Other Images</h2>
            <div class="wrapper" style="margin-top: 50px;">

                {% for item in about_note.images.all %}
                <div class="project-container">
                    <img style="height: 200px; width: 200px;" src="{{item.image.url}}" alt=""
                        class="image-container fit">
                </div>
                {% endfor %}

            </div>
        </div>
        {% endif %}




        {% endif %}

    </div>



    {% endblock content %}

dashboard/templates/dashboard/categories.html
{% extends 'dashboard/header.html' %}

{% load static %}


{% block title %}
Categories
{% endblock title %}



{% block content %}

<head>
    <style>
        a {
            color: #fff;
        }

        #project-categories {
            width: 80%;
            margin: 30px auto;
        }

        .table * {
            overflow-x: auto;
            padding: 10px;
            font-family: 'Prata', sans-serif;

        }

        .table td,
        .table th {
            border: #fff 1px solid;
        }

        a {
            color: #fff;
        }
    </style>
</head>
<section id="project-categories">
    <div id="content">
        <div class="row">
            <h1 style="margin: 50px auto; width: 80%; text-align: center;">Categories</h1>
        </div>
        <div>
            <table class="table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Details</th>
                        <th>Edit</th>
                    </tr>
                </thead>

                <tbody>

                    {% for category in categories %}
                    <tr>
                        <td>{{category.name}}</td>
                        
                        <td><a style="color: #fff;" href="{% url 'dashboard:category_detail' category.pk %}">Details</a>
                        </td>
                        <td><a href="{% url 'dashboard:update_category' category.pk  %}">Update Category</a></td>
                    </tr>
                    {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
</section>

{% endblock content %}

dashboard/templates/dashboard/main_category_detail.html
{% extends 'dashboard/header.html' %}
{% load static %}



{% block title %}
    {{main_category.name}}
{% endblock title %}



{% block content %}
<head>
    <link rel="stylesheet" href="{% static 'home/assets/css/modish.css' %}">
   
    <style>
         #category, #other-categories{
            background-color: #1c1c1c;
            color: #fff;
        } 
    
       
        .table *{
            overflow-x: auto;
            padding: 10px;
            font-family: 'Prata', sans-serif;

        }
        .table td, .table th{
            border: #fff 1px solid;
        }
      
    </style>
</head>

<div id="content">

<section id="category">
    <div class="headline" data-aos="fade-up" data-aos-duration="1000">
        <h1 class="center">{{main_category.name}} <span style="padding-top: 20px; display: block;"></span></h1>
        
    </div>

    <div class="headline" data-aos="flip-left" data-aos-duration="1000">
        <h1 class="center">Categories in {{main_category.name.title}}</h1>
    </div>
    <div class="wrapper">
        
        {% for category in main_category.categories.all %}
            <div class="project-container">
            <h4 class="center">{{category.name.title}}</h4>
          
            
            <h5 class="center"><a class="btn btn btn-white" href="{{category.get_absolute_url}}" style="text-align:center 
            ;">See More</a></h5>
                
            </div>
        {% endfor %}
            
        
            
    </div>
</section>
    <section id="other-categories" style="margin: 50px auto;">
    <div class="container headline"  data-aos="zoom-in" data-aos-duration="1000">
        <h1  >
            Other Categories
        </h1>
        <div class="wrapper">
            
            {% for cat in other_categories %}
            <div class="container">
                <a class="btn btn-white btn-large" href="{{cat.get_absolute_url}}">{{cat.name}}</a>
            </div>
                
            {% endfor %}
                
        </div>
    </div>    
    </section> 
    
    </div>
{% endblock content %}


{% block footer %}
    
{% endblock footer %}
    
    
    

dashboard/templates/dashboard/post_confirm_delete.html
{% extends 'dashboard/header.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block title %}

{% endblock title %}


{% block content %}

<div class="row" style="margin-top: 50px;">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <h4 class="card-title mb-5 center"><span class="alert alert-danger">You are about to delete {{object.heading}}. Please confrim below</span></h4>
            <div class="card-body">
                <div class="d-flex flex-row justify-content-center">


                    <form class="form-body" action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form.media}}
                        {{form|crispy}}
                        <button type="submit" class="badge badge-outline-danger">
                           Confirm
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    
</div>

{% endblock content %}

dashboard/templates/dashboard/post_detail.html
{% extends 'dashboard/header.html' %}
{% load static %}


{% block title %}
    {{post.heading}}  {{post.created}}
{% endblock title %}



{% block content %}
<head>
    <style>
        
    </style>
</head>
<div class="row col-12 pt-5" style="margin: 100px auto;">
    
    {% if post %}
        
        <div class=" card">
            <h2 >{{post.heading}} <span>
                    <blockquote>{{post.created}}</blockquote>
                </span></h2>
                {% if post.image %}
                <img class="card-img" src="{{post.image.url}}" alt="">
                
                {% endif %}

        </div>
 

        <div class="subheading" >
            <h4 >{{post.subheading}}</h4>
           
                <h5 >{{post.content}}</h5>
            
        </div>
        <div class="container"  style="margin-top: 80px;display: flex; margin-left: 10px;">
            <h4><a class="badge badge-outline-light" href="{% url 'dashboard:post_images' post.pk %}">Add Images</a></h4>
            <h5><a class="badge badge-outline-success" href="{% url 'dashboard:update_post' post.pk %}">Update</a><span><a class="badge badge-outline-danger" href="{% url 'dashboard:delete_post' post.pk %}">Delete</a></span></h5>
        </div>

        
        {% if post.images %}

        <div class="row">

        
            <div class=" span12  mt-5">
                <h2 class="center"> Other Images</h2>
                <div class="wrapper" style="margin-top: 50px;">
                
                {% for item in post.images.all %}
                    <div class="project-container">
                        <img style="height: 200px; width: 200px;" src="{{item.image.url}}" alt="" class="image-container fit">
                    </div>
                {% endfor %}
                    
                </div>
            </div>
        {% endif %}
            

       
            
    {% endif %}
        
</div>


    
{% endblock content %}
    
    

dashboard/templates/dashboard/press_notes.html
{% extends 'dashboard/header.html' %}
{% load static %}



{% block title %}
Press

{% endblock title %}



{% block content %}

<div class="row">
    <div class="col-12">
        <h1 class="center mt-5">Press</h1>

        {% for press in press_notes %}
        <p><a href="{% url 'dashboard:press_detail' press.pk %}">{{press.content|safe}}</a></p>
        {% endfor %}

    </div>
</div>

{% endblock content %}

dashboard/templates/dashboard/resources.html
{% extends 'dashboard/header.html' %}
{% load static %}



{% block title %}
Resources
    
{% endblock title %}



{% block content %}

<div class="row">
    <div class="col-12">
        <h1 class="center mt-5">Resources</h1>
        
        {% for resource in resources %}
            <p><a href="{% url 'dashboard:resource_detail' resource.pk %}">{{resource.content|safe}}</a></p>
        {% endfor %}
            
    </div>
</div>
    
{% endblock content %}
    

dashboard/templates/dashboard/slack.html
{% extends 'dashboard/header.html' %}


{% block title %}
    Slack
{% endblock title %}



{% block content %}
<head>
    <style>
        li{
            list-style: none;
        }
        a{
            text-decoration: none;
        }
    </style>
</head>
<div class="row">
    <div class="col-12">
        <div class="container">
            <h1>ADM Slack Connect</h1>
        </div>
        <nav >
        <div class="container" style="display: flex; gap: 10px;">
            <li><a class="btn btn-light" href="{% url 'dashboard:list_slack_channels' %}">List Channels</a></li>
            <li><a class="btn btn-light" href="{% url 'dashboard:create_channel' %}">Create New Channel</a></li>
        
        </div>
           
        </nav>
    </div>
</div>
    
{% endblock content %}
    
    

dashboard/templates/dashboard/users.html
{% extends 'dashboard/header.html' %}
{% load static %}


{% block title %}Site Users{% endblock title %}

{% block content %}
<head></head>
<section id="intro">
    <div class="table-responsive">
        <table id="table" class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>User Type</th>
                    <th>Date Joined</th>
                    <th>Action</th>
                    <th>Moderation</th>
                    <th>Details</th>
                   
                </tr>
            </thead>

            <tbody>
                
                {% for user in users %}
                    <tr>
                       <td> {{user.get_full_name.title}}
                        {% if user.is_paragon %} <span class="badge badge-outline-danger">
                           
                           
                               Paragon
                               </span>
                           {% endif %}
                               
                      </td>
                        <td>
                            
                            {% if user.is_superuser %}
                                <span class="badge badge-danger">Admin
                            {% elif user.is_moderator %}
                            <span class="badge badge-warning">Moderator
                            {% elif user.is_designer %}
                            <span class="badge badge-success">Creative
                            {% elif user.is_student %}
                            <span class="badge badge-info">Student
                                {% elif user.is_paragon %}
                                <span class="btn btn-danger">Paragon</span>
                            {% endif %}
                                
                        </td>
                        
                        <td>{{user.date_joined}}</td>
                      
                        <td><a class="btn btn-dark btn-outline-danger" href="{% url 'dashboard:enable_paragon' user.pk %}">Activate Paragon</a></td>

                        <td>
                            
                            {% if user.is_moderator %}
                                <a class="btn btn-dark btn-outline-danger" href="{% url 'dashboard:disable_moderator' user.pk %}">Disable Moderator</a>
                                {% else %}
                                <a class="btn btn-dark btn-outline-danger" href="{% url 'dashboard:enable_moderator' user.pk %}">Enable Moderator</a>
                                {% endif %}
                                
                            
                        </td>
                        <td><a class="badge badge-outline-dark" href="{% url 'dashboard:user_detail' user.pk %}">Check Details</a></td>
                    </tr>
                  
                        
                {% endfor %}
                    

            </tbody>    

        </table>
    </div>
</section>


{% block javascript %}

<script>
    $(document).ready(function () {
        $('#table').DataTable({

        });
    });
</script>
    
{% endblock javascript %}
    
    
{% endblock content %}
    
    